### ISSUE TITLE
Wrong Problem id

### ISSUE THREAD

**Issue by ayonization** [agrawal-d/cph-submit#1]
When I press the submit button, the extension simply enters "problemC" in the codeforces submission page "Problem :" box and not the problem id.
Thus codeforces says "No such problem" and does not submit the solution.

**Comment by agrawal-d** [comment]
Which problem are you trying to submit? Please share the full problem URL.

**Comment by ayonization** [comment]
[https://codeforces.com/contest/1398/problem/C]

**Comment by ayonization** [comment]
[](https://codeforces.com/contest/1398/problem/C)

**Comment by ayonization** [comment]
https://codeforces.com/contest/1398/problem/C

Browser is firefox and I am not submitting during the contest.

**Comment by ayonization** [comment]
![FireShot Capture 003 - Submit - Codeforces - codeforces com](https://user-images.githubusercontent.com/62653441/90338012-30b6d180-e004-11ea-9ce2-1e683546faed.png)

**Comment by agrawal-d** [comment]
Thanks. I've fixed the issue.
Please update CPH to v4.3.5 from VS Code.
