### ISSUE TITLE
chrome support

### ISSUE THREAD

**Issue by urparvezali** [agrawal-d/cph-submit#10]
need this feature on chromium or chrome browser

**Comment by aadarshkt** [comment]
Yeah of course. Someone has made this. [cph-submit-chrome](https://github.com/abdallamaher/cph-submit).
But I am having a problem loading it unpacked. In extension page it says this.

![Screenshot 2022-11-08 114827](https://user-images.githubusercontent.com/72285744/200489634-11990722-16bb-406e-891b-0f7b46236e92.png)

**Comment by urparvezali** [comment]
I'm also facing this

**Comment by abdallamaher** [comment]
thank you for raising this :
1. Install npm
2. Clone this Repository
3. Make Sure To use `Node 16.13.0`
4. Run `npm install`
5. Run `npm run webpack`
6. Load Extension to Google Chrome as unpacked.

**Comment by pota2dev** [comment]
> thank you for raising this :
> 
> 1. Install npm
> 2. Clone this Repository
> 3. Make Sure To use `Node 16.13.0`
> 4. Run `npm install`
> 5. Run `npm run webpack`
> 6. Load Extension to Google Chrome as unpacked.

Tried these steps. Still getting the same error as @aadarshkt mentioned.

**Comment by urparvezali** [comment]
after installing npm do  solve the vulnarabilities by the instructed command and thus will work
